import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import MateriaButton from "../../components/MateriaButton";

import { api } from "../../utils/api";

const MateriaDetail: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const intId = parseInt(id! as string);
  const materia = api.materia.getPreviasById.useQuery({ id: intId });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-20 bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {materia.data && (
          <>
            {materia.data.previas.length ? (
              <div>
                <h2 className="py-2 text-center text-xl font-semibold text-white">
                  Previas
                </h2>
                <div className="flex flex-wrap items-center justify-center gap-2">
                  {materia.data.previas.map(
                    ({ materia_previa: { nombre, id } }) => (
                      <MateriaButton id={id} nombre={nombre} />
                    )
                  )}
                </div>
              </div>
            ) : (
              <h2 className="py-2 text-center text-xl font-semibold text-white">
                Esta materia no tiene previas
              </h2>
            )}

            <MateriaButton
              id={materia.data.id}
              nombre={materia.data.nombre}
              principal
            />

            {materia.data.siguientes.length ? (
              <div className="text-center">
                <div className="flex flex-wrap items-center justify-center gap-2">
                  {materia.data.siguientes.map(
                    ({ materia_siguiente: { nombre, id } }) => (
                      <MateriaButton id={id} nombre={nombre} />
                    )
                  )}
                </div>
                <h2 className="py-2 text-center text-xl font-semibold text-white">
                  Siguientes
                </h2>
              </div>
            ) : (
              <h2 className="py-2 text-center text-xl font-semibold text-white">
                Esta materia no tiene siguientes
              </h2>
            )}
          </>
        )}
      </main>
    </>
  );
};

export default MateriaDetail;
