import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import { api } from "../../utils/api";

const MateriaDetail: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const intId = parseInt(id! as string);
  const materia = api.materia.getPreviasById.useQuery({ id: intId });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {materia.data && (
          <Link href={`/materia/${materia.data.id}`}>
            <div className="w-100 my-2 border-2 border-black bg-white py-5">
              <span className="border-r-4 px-4">{materia.data.id}</span>
              <span className="px-4">{materia.data.nombre}</span>
            </div>
          </Link>
        )}
        {materia.data && (
          <p className="bg-white">
            Previas: {JSON.stringify(materia.data.previas)}
          </p>
        )}
        {materia.data && (
          <p className="bg-white">
            Siguientes: {JSON.stringify(materia.data.siguientes)}
          </p>
        )}
      </main>
    </>
  );
};

export default MateriaDetail;
