import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "../utils/api";

const Home: NextPage = () => {
  const materia = api.materia.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-row flex-wrap justify-center gap-2 bg-gradient-to-b from-[#2e026d] to-[#15162c] p-5">
        {materia.data?.map(({ id, nombre }) => (
          <Link href={`/materia/${id}`}>
            <div className="w-100 border-2 border-black bg-white py-5">
              <span className="border-r-4 px-4">{id}</span>
              <span className="px-4">{nombre}</span>
            </div>
          </Link>
        ))}
      </main>
    </>
  );
};

export default Home;
